import React from 'react';
import { Metadata } from 'next';
import CartList from '@/components/Cart/CartList';


export const metadata: Metadata = {
  title: "Comforty | Cart Page",
  description: "Generated by create next app",
};

const ShoppingCart = () => {
  
  return (
      
      <div className="max-w-7xl mx-auto p-6">
        <CartList/>
      </div>
    );
};

export default ShoppingCart;
