import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { CartContextProvider } from "@/context/CartContext";


export const metadata: Metadata = {
  title: "Comforty | Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartContextProvider>
        <Header/>
        {children}
        <Footer/>

        </CartContextProvider>
      </body>
    </html>
  );
}
